name: Build and Deploy

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install
        run: |
          bun install

      - name: Build
        run: |
          bun run build

      - name: Lint
        run: |
          bun run lint-staged

      - name: E2E
        run: |
          bun run test:e2e
